#!/usr/bin/env bash
# Update package list and upgrade all packages
sudo apt update -y
sudo apt upgrade -y

# Install Nginx
sudo apt install nginx -y

# Start and enable Nginx service
sudo systemctl start nginx
sudo systemctl enable nginx

# Configure Nginx to include a custom header in its HTTP response
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
    location / {
        add_header X-Served-By $HOSTNAME;
    }
}' | sudo tee /etc/nginx/sites-available/default
sudo nginx -t
# Restart Nginx to apply the changes
sudo systemctl restart nginx
