#!/usr/bin/bash
#Create a tar archive of sql backups

MYSQL_DUMP="backup.sql"
DATE_FORMAT="$(date +'%d-%m-%Y')"
mysqldump -uroot -p"$1" --all-databases > "$MYSQL_DUMP"
tar -czf "$DATE_FORMAT.tar.gz" "$MYSQL_DUMP"
